Repository FRONTENDSCHOOL10/12Gain, pull requests merged in 2024-09, with the labels that each got.

#3 Feat: input component
  src/app/App.jsx
  src/components/InputWithDelete.jsx
Labels: feature

#4 Feature/icons/kss
  .github/PULL_REQUEST_TEMPLATE.md
  index.html
  package.json
  pnpm-lock.yaml
  public/react.svg
  public/stack.svg
  src/app/App.jsx
  src/components/GlobalNav/GlobalNav.jsx
  src/components/GlobalNav/style.module.css
  src/components/Icon/Icon.jsx
  src/components/Icon/style.module.css
  src/routes/RootLayout.jsx
  src/routes/community/index.jsx
  src/routes/home/index.jsx
  src/routes/myAppointment/index.jsx
  src/routes/profile/index.jsx
  src/routes/router.jsx
  src/stores/route.js
Labels: documentation, Completed, feature, css styling

#9 [feat] #5 : 공통 버튼 컴퍼넌트 구현
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
Labels: feature

#11 [feat] #6 : profile 페이지 마크업 중
  public/profile.png
  src/app/App.jsx
  src/components/Icon/Icon.jsx
  src/components/ProfileImage/ProfileImage.jsx
  src/components/ProfileImage/ProfileImage.module.css
  src/routes/profile/component/MyInterestList.jsx
  src/routes/profile/component/MyInterestList.module.css
  src/routes/profile/component/header.jsx
  src/routes/profile/component/header.module.css
  src/routes/profile/component/profileCard.jsx
  src/routes/profile/component/profileCard.module.css
  src/routes/profile/index.jsx
  src/routes/profile/style.module.css
Labels: in progress

#12 [refactory] icon 컴포넌트 사용 / zustand 상태 관리
  src/app/App.jsx
  src/components/Input/InputWithDelete.jsx
  src/stores/route.js
Labels: refactoring

#16 [refactory] type prop의 타입 변경
  src/components/Input/InputWithDelete.jsx
Labels: enhancement, refactoring

#18 [feat] main 페이지
  public/running.png
  src/components/Post/Post.jsx
  src/components/PostDetail/PostDetail.jsx
  src/components/PostDetail/style.module.css
  src/routes/home/component/MainPost.jsx
  src/routes/home/component/MainPost.module.css
  src/routes/home/component/MainPostList.jsx
  src/routes/home/component/MainPostList.module.css
  src/routes/home/component/header.jsx
  src/routes/home/component/header.module.css
  src/routes/home/index.jsx
  src/routes/home/style.module.css
  src/routes/router.jsx
  src/stores/route.js
Labels: feature, in progress, mark up

#23 [feat] 메인 페이지
  src/components/PostDetail/PostDetail.jsx
  src/routes/home/component/AttendPost.jsx
  src/routes/home/component/AttendPost.module.css
  src/routes/home/component/header.jsx
  src/routes/home/component/header.module.css
  src/routes/home/index.jsx
  src/routes/router.jsx
Labels: in progress, mark up, refactoring

#25 Feature/community/kjy
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
  src/components/KebabMenu/KebabMenu.jsx
  src/routes/community/CreateFeedPage.jsx
  src/routes/community/component/BtnChat.jsx
  src/routes/community/component/BtnCount.module.css
  src/routes/community/component/BtnCreateFeed.jsx
  src/routes/community/component/BtnThumsup.jsx
  src/routes/community/component/Feed.jsx
  src/routes/community/component/FeedProfile.jsx
  src/routes/community/component/FeedProfile.module.css
  src/routes/community/component/TimeAgo.jsx
  src/routes/community/index.jsx
  src/routes/community/style.module.css
  src/routes/router.jsx
Labels: feature, in progress, mark up, css styling

#24 Feature/login/psy
  src/components/Input/InputWithDelete.jsx
  src/components/Input/style.module.css
  src/routes/home/component/header.jsx
  src/routes/landing/component/LandingLogo.jsx
  src/routes/landing/component/LandingLogo.module.css
  src/routes/landing/component/SignupLink.jsx
  src/routes/landing/component/SignupLink.module.css
  src/routes/landing/index.jsx
  src/routes/landing/style.module.css
  src/routes/login/component/EmailInput.jsx
  src/routes/login/component/FormGroup.jsx
  src/routes/login/component/FormGroup.module.css
  src/routes/login/component/PasswordInput.jsx
  src/routes/login/index.jsx
  src/routes/login/style.module.css
  src/routes/router.jsx
  src/routes/signup/index.jsx
  src/stores/route.js
  src/styles/_font.css
  src/styles/main.css
Labels: feature, mark up

#27 [refactory] 메인 페이지
  src/routes/home/index.jsx
Labels: refactoring

#32 Feature/signup/psy
  package.json
  pnpm-lock.yaml
  public/stack.svg
  src/components/Input/InputWithDelete.jsx
  src/components/Toast/ToastPopUp.jsx
  src/components/Toast/ToastPopUp.module.css
  src/routes/landing/component/LandingLogo.jsx
  src/routes/landing/component/LandingLogo.module.css
  src/routes/landing/component/SignupLink.jsx
  src/routes/landing/component/SignupLink.module.css
  src/routes/landing/index.jsx
  src/routes/landing/style.module.css
  src/routes/login/component/EmailInput.jsx
  src/routes/login/component/FormGroup.jsx
  src/routes/login/component/FormGroup.module.css
  src/routes/login/component/PasswordInput.jsx
  src/routes/login/index.jsx
  src/routes/login/style.module.css
  src/routes/signup/component/EmailStep.jsx
  src/routes/signup/component/EmailStep.module.css
  src/routes/signup/component/PasswordStep.jsx
  src/routes/signup/component/PasswordStep.module.css
  src/routes/signup/component/PhoneStep.jsx
  src/routes/signup/component/PhoneStep.module.css
  src/routes/signup/component/ProgressBar.jsx
  src/routes/signup/component/ProgressBar.module.css
  src/routes/signup/component/SignUpLogo.jsx
  src/routes/signup/component/SignUpLogo.module.css
  src/routes/signup/component/TermsItem.jsx
  src/routes/signup/component/TermsItem.module.css
  src/routes/signup/component/TermsStep.jsx
  src/routes/signup/component/TermsStep.module.css
  src/routes/signup/index.jsx
  src/stores/route.js
Labels: in progress, mark up, refactoring

#34 Feature/community/kjy
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
  src/components/KebabMenu/KebabMenu.jsx
  src/components/KebabMenu/style.module.css
  src/components/TextArea/TextArea.jsx
  src/components/TextArea/style.module.css
  src/routes/community/CommentPage/CommentPage.jsx
  src/routes/community/CommentPage/CommentPage.module.css
  src/routes/community/CreateFeedPage.jsx
  src/routes/community/CreateFeedPage.module.css
  src/routes/community/CreateFeedPage/CreateFeedPage.jsx
  src/routes/community/CreateFeedPage/CreateFeedPage.module.css
  src/routes/community/component/AddComment.jsx
  src/routes/community/component/AddComment.module.css
  src/routes/community/component/AddCommentProfile.jsx
  src/routes/community/component/AddCommentProfile.module.css
  src/routes/community/component/BtnChat.jsx
  src/routes/community/component/BtnComment.jsx
  src/routes/community/component/BtnCount.module.css
  src/routes/community/component/BtnCreateFeed.jsx
  src/routes/community/component/BtnCreateFeed.module.css
  src/routes/community/component/BtnThumsup.jsx
  src/routes/community/component/Feed.jsx
  src/routes/community/component/Feed.module.css
  src/routes/community/index.jsx
  src/routes/community/style.module.css
  src/routes/profile/EditProfile/EditProfile.jsx
  src/routes/profile/EditProfile/EditProfile.module.css
  src/routes/profile/component/PostList.module.css
  src/routes/profile/component/profileCard.module.css
  src/routes/profile/index.jsx
  src/routes/profile/style.module.css
  src/routes/router.jsx
Labels: feature, in progress, mark up, refactoring, css styling

#41 [refactory]header, button styling 변경, router 수정
  src/components/PostDetail/PostDetail.jsx
  src/components/PostDetail/style.module.css
  src/routes/attendpost/index.jsx
  src/routes/attendpost/style.module.css
  src/routes/post/component/NewPost.jsx
  src/routes/post/component/NewPost.module.css
  src/routes/router.jsx
Labels: refactoring, css styling

#39 Feature/community/kjy
  src/routes/community/CommentPage/CommentPage.jsx
  src/routes/community/CommentPage/CommentPage.module.css
  src/routes/community/CreateFeedPage/CreateFeedPage.jsx
  src/routes/community/CreateFeedPage/CreateFeedPage.module.css
  src/routes/community/component/BtnComment.jsx
  src/routes/community/component/BtnCount.module.css
  src/routes/community/component/BtnCreateFeed.module.css
  src/routes/community/component/BtnThumsup.jsx
  src/routes/community/style.module.css
  src/routes/router.jsx
Labels: mark up, css styling

#42 Feature/login signup/psy
  src/app/App.jsx
  src/components/Input/style.module.css
  src/components/Toast/ToastPopUp.jsx
  src/components/Toast/ToastPopUp.module.css
  src/components/Tooltip/Tooltip.jsx
  src/components/Tooltip/Tooltip.module.css
  src/routes/landing/component/LandingLogo.module.css
  src/routes/landing/index.jsx
  src/routes/landing/style.module.css
  src/routes/login/index.jsx
  src/routes/login/style.module.css
  src/routes/signup/component/EmailStep.jsx
  src/routes/signup/component/EmailStep.module.css
  src/routes/signup/component/PasswordStep.jsx
  src/routes/signup/component/PasswordStep.module.css
  src/routes/signup/component/PhoneStep.jsx
  src/routes/signup/component/PhoneStep.module.css
  src/routes/signup/component/TermsStep.jsx
  src/routes/signup/component/TermsStep.module.css
  src/routes/signup/index.jsx
Labels: feature, mark up, refactoring

#48 Feature/button css/kjy
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
  src/components/KebabMenu/style.module.css
  src/styles/_utils.css
Labels: css styling

#52 Feature/swiper/kjy
  package.json
  pnpm-lock.yaml
  src/api/getRecords.js
  src/routes/home/banner/Banner.jsx
  src/routes/home/banner/Banner.module.css
  src/routes/home/index.jsx
Labels: feature

#54 Feature/community button/kjy
  src/components/Button/Button.jsx
  src/components/TextArea/TextArea.jsx
  src/routes/community/CreateFeedPage/CreateFeedPage.jsx
  src/routes/community/CreateFeedPage/CreateFeedPage.module.css
  src/routes/community/component/AddComment.module.css
  src/routes/community/component/BtnCreateFeed.jsx
  src/routes/community/component/BtnCreateFeed.module.css
  src/routes/community/component/BtnThumsup.jsx
  src/routes/community/component/FeedProfile.module.css
  src/routes/community/style.module.css
  src/styles/_reset.css
Labels: refactoring, css styling

#56 Feature/login/hsy
  src/components/PostDetail/style.module.css
  src/routes/attendpost/style.module.css
  src/routes/login/index.jsx
  src/routes/post/component/NewPost.module.css
Labels: feature, refactoring

#58 Feature/home render/psy
  package.json
  pnpm-lock.yaml
  src/routes/home/component/MainPost.jsx
  src/routes/home/index.jsx
  src/routes/landing/index.jsx
  src/routes/login/component/EmailInput.jsx
  src/stores/form.js
  src/stores/postStore.js
Labels: feature, mark up

#57 Feature/home/kss
  src/components/Button/Checkbox.jsx
  src/components/Button/IconButton.jsx
  src/components/Button/IconButton.module.css
  src/components/Button/PostButton.jsx
  src/components/Button/PostButton.module.css
  src/components/Button/RadioBox.jsx
  src/components/Button/RadioBox.module.css
  src/components/ChoiceInput/ChoiceInput.jsx
  src/components/ChoiceInput/style.module.css
  src/components/ImageUpload/ImageUpload.jsx
  src/components/ImageUpload/ImageUpload.module.css
  src/components/PostInput/PostInput.jsx
  src/components/PostInput/style.module.css
  src/components/PostTextarea/PostTextarea.jsx
  src/components/PostTextarea/style.module.css
  src/components/TextArea/TextArea.jsx
  src/components/TextArea/style.module.css
  src/routes/community/CreateFeed/CreateFeed.module.css
  src/routes/community/CreateFeed/index.jsx
  src/routes/community/CreateFeedPage/CreateFeedPage.jsx
  src/routes/community/CreateFeedPage/CreateFeedPage.module.css
  src/routes/community/component/Feed.jsx
  src/routes/community/index.jsx
  src/routes/community/style.module.css
  src/routes/home/CreatePost/CreatePost.module.css
  src/routes/home/CreatePost/index.jsx
  src/routes/home/SelectCategory/SelectCategory.module.css
  src/routes/home/SelectCategory/index.jsx
  src/routes/home/component/MainPost.module.css
  src/routes/home/component/MainPostList.module.css
  src/routes/home/component/header.jsx
  src/routes/home/component/header.module.css
  src/routes/home/index.jsx
  src/routes/home/style.module.css
  src/routes/post/component/NewPost.jsx
  src/routes/post/component/NewPost.module.css
  src/routes/post/index.jsx
  src/routes/post/style.module.css
  src/routes/router.jsx
  src/stores/form.js
  src/styles/_reset.css
Labels: createData, feature, in progress

#61 Feature/auth button/psy
  src/routes/landing/style.module.css
  src/routes/login/component/PasswordInput.jsx
  src/routes/login/style.module.css
  src/routes/signup/component/EmailStep.module.css
  src/routes/signup/component/PasswordStep.module.css
  src/routes/signup/component/PhoneStep.module.css
  src/routes/signup/component/TermsStep.module.css
Labels: css styling

#65 refactory/hsy
  src/components/Input/InputWithDelete.jsx
  src/components/PostButton/PostButton.jsx
  src/components/PostDetail/PostDetail.jsx
  src/routes/attendpost/index.jsx
Labels: refactoring

#66 Feature/home filter/psy
  src/components/Post/style.module.css
  src/routes/home/component/MainPost.jsx
  src/routes/home/index.jsx
  src/routes/login/component/EmailInput.jsx
  src/routes/login/index.jsx
  src/routes/signup/component/EmailStep.jsx
  src/routes/signup/component/PasswordStep.jsx
  src/routes/signup/component/PhoneStep.jsx
  src/routes/signup/component/TermsStep.jsx
  src/routes/signup/index.jsx
  src/stores/authStore.js
  src/stores/postStore.js
  src/stores/route.js
Labels: refactoring

#69 refactory/hsy
  src/components/Input/InputWithDelete.jsx
Labels: refactoring

#70 Feature/post details/kss
  src/api/getPbImageURL.js
  src/components/DetailItem/DetailItem.jsx
  src/components/Post/Post.jsx
  src/components/PostDetail/PostDetail.jsx
  src/components/PostManager/PostManager.jsx
  src/components/ProfileImage/ProfileImage.jsx
  src/routes/home/component/MainPost.jsx
  src/routes/postDetails/component/PostDetailsImage.jsx
  src/routes/postDetails/component/PostDetailsImage.module.css
  src/routes/postDetails/index.jsx
  src/routes/postDetails/postDetails.module.css
  src/routes/router.jsx
Labels: feature, in progress

#72 [feat] 회원관리 기능 및 참여한 모임 조회 기능 개발
  package.json
  pnpm-lock.yaml
  src/routes/login/component/EmailInput.jsx
  src/routes/login/index.jsx
  src/routes/login/style.module.css
  src/routes/myAppointment/component/MyPost.jsx
  src/routes/myAppointment/component/MyPost.module.css
  src/routes/myAppointment/component/MyPostList.jsx
  src/routes/myAppointment/component/MyPostList.module.css
  src/routes/myAppointment/index.jsx
  src/routes/myAppointment/style.module.css
  src/routes/profile/DeleteAccount/DeleteAccount.module.css
  src/routes/profile/DeleteAccount/index.jsx
  src/routes/profile/Setting/Setting.module.css
  src/routes/profile/Setting/index.jsx
  src/routes/profile/component/SettingList.jsx
  src/routes/signup/component/EmailAuthStep.jsx
  src/routes/signup/component/EmailAuthStep.module.css
  src/routes/signup/component/EmailStep.jsx
  src/routes/signup/component/NicknameStep.jsx
  src/routes/signup/component/NicknameStep.module.css
  src/routes/signup/component/PasswordStep.jsx
  src/routes/signup/component/PhoneStep.jsx
  src/routes/signup/component/TermsStep.jsx
  src/routes/signup/index.jsx
  src/stores/authStore.js
  src/stores/form.js
Labels: createData, feature, refactoring, css styling

#74 Feature/post details/kss
  src/components/PostManager/PostManager.jsx
  src/components/PostManager/PostManager.module.css
  src/routes/community/CreateFeed/CreateFeed.module.css
  src/routes/home/CreatePost/CreatePost.module.css
  src/routes/home/CreatePost/index.jsx
  src/routes/postDetails/index.jsx
  src/routes/postDetails/postDetails.module.css
  src/stores/form.js
  src/stores/join.js
  src/stores/users.js
Labels: createData, feature

#78 [refactory] css style 수정, 주석 제거
  src/components/Input/InputWithDelete.jsx
  src/components/PostDetail/PostDetail.jsx
  src/components/PostManager/PostManager.jsx
  src/routes/community/CreateFeed/index.jsx
  src/routes/login/component/EmailInput.jsx
  src/routes/myAppointment/component/MyPost.jsx
  src/routes/profile/DeleteAccount/DeleteAccount.module.css
  src/routes/profile/DeleteAccount/index.jsx
  src/routes/profile/Setting/Setting.module.css
  src/routes/profile/Setting/index.jsx
  src/routes/profile/component/SettingList.jsx
  src/routes/signup/component/EmailAuthStep.jsx
  src/routes/signup/component/EmailStep.jsx
  src/routes/signup/component/NicknameStep.jsx
  src/routes/signup/component/PasswordStep.jsx
  src/routes/signup/component/TermsItem.module.css
  src/routes/signup/component/TermsStep.jsx
  src/routes/signup/index.jsx
  src/stores/authStore.js
  src/stores/form.js
Labels: refactoring, css styling

#79 Feature/filter/psy
  src/routes/community/component/Feed.jsx
  src/routes/community/index.jsx
  src/routes/home/index.jsx
  src/routes/router.jsx
  src/stores/communityStore.js
  src/stores/postStore.js
  src/stores/route.js
Labels: createData, feature, in progress

#82 [feat] 커뮤니티 및 홈 렌더링 수정
  src/routes/community/component/Feed.jsx
  src/routes/community/component/FeedProfile.jsx
  src/routes/community/component/TimeAgo.jsx
  src/routes/community/index.jsx
  src/routes/home/index.jsx
  src/routes/router.jsx
  src/stores/postStore.js
  src/stores/route.js
Labels: createData, feature

#84 [refactory] 탈퇴하기 check button 수정, 랜딩 페이지 버튼수정
  src/routes/landing/style.module.css
  src/routes/profile/DeleteAccount/DeleteAccount.module.css
  src/routes/profile/DeleteAccount/index.jsx
Labels: refactoring, css styling

#91 [feat] netlify.toml 파일 생성
  netlify.toml
  src/routes/landing/index.jsx
  src/routes/postDetails/index.jsx
Labels: Build test

#93 [feat] redirects 파일 추가
  netlify.toml
Labels: bug

#95 Feature/postdetail/kss
  src/components/PostManager/PostManager.jsx
  src/components/PostManager/PostManager.module.css
  src/routes/community/Comment/Comment.jsx
  src/routes/community/component/Feed.jsx
  src/routes/community/component/MainFeed.jsx
  src/routes/community/index.jsx
  src/routes/postDetails/index.jsx
  src/routes/router.jsx
  src/stores/join.js
Labels: refactoring

#97 Feature/profileinfo/kjy
  src/components/Button/Checkbox.jsx
  src/components/Button/IconButton.jsx
  src/components/HeaderForDetails/HeaderForDetails.jsx
  src/components/HeaderForDetails/HeaderForDetails.module.css
  src/components/ImageUpload/ImageUpload.jsx
  src/components/KebabMenu/KebabMenu.jsx
  src/components/PostDetail/PostDetail.jsx
  src/components/TextArea/TextArea.jsx
  src/components/TextArea/style.module.css
  src/routes/postDetails/index.jsx
  src/routes/profile/DeleteAccount/index.jsx
  src/routes/profile/EditInterest/index.jsx
  src/routes/profile/EditProfile/EditProfile.module.css
  src/routes/profile/EditProfile/index.jsx
  src/routes/profile/EditProfile/zzzz.jsx
  src/routes/profile/Setting/index.jsx
  src/routes/profile/index.jsx
  src/stores/kebabStore.js
  src/stores/users.js
  src/styles/_utils.css
Labels: createData, feature, refactoring, css styling

#100 Feature/filtering/psy
  src/components/Post/Post.jsx
  src/routes/home/component/MainPost.jsx
  src/routes/home/index.jsx
  src/stores/communityStore.js
  src/stores/postStore.js
Labels: createData, feature

#102 Feature/join/hsy
  src/routes/home/style.module.css
  src/routes/myAppointment/component/MyPost.jsx
  src/routes/myAppointment/style.module.css
  src/routes/profile/DeleteAccount/DeleteAccount.module.css
  src/routes/profile/DeleteAccount/index.jsx
  src/routes/signup/component/EmailAuthStep.module.css
  src/routes/signup/component/EmailStep.jsx
  src/routes/signup/component/NicknameStep.module.css
  src/routes/signup/component/TermsStep.jsx
  src/routes/signup/component/TermsStep.module.css
Labels: enhancement, refactoring

#107 Feature/mypost/kjy
  public/logo.webp
  src/components/Confirm/Confirm.jsx
  src/components/Confirm/Confirm.module.css
  src/components/GlobalNav/style.module.css
  src/routes/RootLayout.jsx
  src/routes/community/style.module.css
  src/routes/home/SelectCategory/SelectCategory.module.css
  src/routes/home/SelectCategory/index.jsx
  src/routes/home/style.module.css
  src/routes/myAppointment/component/MyPost.module.css
  src/routes/profile/component/FeedCard.jsx
  src/routes/profile/component/MyFeed.jsx
  src/routes/profile/component/MyFeed.module.css
  src/routes/profile/component/MyPost.jsx
  src/routes/profile/component/MyPost.module.css
  src/routes/style.module.css
Labels: feature, refactoring, css styling

#109 Feature/404page/kjy
  src/components/KebabMenu/style.module.css
  src/routes/notFound/index.jsx
  src/routes/notFound/style.module.css
  src/routes/router.jsx
Labels: mark up, refactoring, css styling

#112 Feature/banner/psy
  README.md
  netlify.toml
  package.json
  pnpm-lock.yaml
  public/_redirects
  src/components/Post/Post.jsx
  src/routes/community/component/Feed.jsx
  src/routes/community/index.jsx
  src/routes/home/banner/Banner.jsx
  src/routes/home/component/MainPost.jsx
  src/stores/communityStore.js
  src/stores/postStore.js
  src/styles/_font.css
Labels: documentation, createData, refactoring

#113 Feature/image/kjy
  src/components/Post/Post.jsx
  src/routes/community/component/Feed.jsx
  src/routes/community/component/FeedProfile.jsx
  src/routes/home/component/MainPost.jsx
  src/routes/profile/component/MyFeed.jsx
Labels: feature, refactoring

#120 Feature/mypost/hsy
  src/components/Button/IconButton.jsx
  src/components/PostDetail/PostDetail.jsx
  src/routes/myAppointment/index.jsx
  src/routes/router.jsx
  src/routes/search/index.jsx
  src/routes/search/style.module.css
  src/routes/signup/component/EmailStep.jsx
  src/routes/style.module.css
Labels: feature, mark up, refactoring

#122 [refactory] 검색 페이지
  src/components/Post/Post.jsx
  src/routes/search/index.jsx
  src/routes/search/style.module.css
Labels: enhancement

#123 Feature/kebabmenu/kjy
  src/components/KebabMenu/KebabMenu.jsx
  src/routes/community/component/Feed.jsx
  src/routes/profile/component/FeedCard.jsx
  src/routes/profile/component/MyFeed.jsx
  src/stores/kebabStore.js
Labels: refactoring

#127 [feat] 파일수정
  src/routes/myAppointment/component/MyPost.jsx
Labels: refactoring

#129 [refactory] mypost list
  src/routes/myAppointment/component/MyPost.jsx
Labels: enhancement

#130 Refactory/kjy
  src/routes/chatList/ChatRoom/ChatRoom.module.css
  src/routes/chatList/ChatRoom/index.jsx
  src/routes/profile/component/MyFeed.jsx
  src/routes/profile/component/MyFeed.module.css
  src/styles/_reset.css
Labels: refactoring, css styling

#132 [refactory] 경로 수정
  src/components/KebabMenu/KebabMenu.jsx
  src/routes/community/CreateFeed/index.jsx
Labels: refactoring

#136 [refactory] 케밥메뉴 수정
  src/components/KebabMenu/KebabMenu.jsx
  src/routes/community/component/Feed.jsx
  src/routes/profile/component/FeedCard.jsx
  src/stores/kebabStore.js
Labels: refactoring
